config {
  type: "assertion",
  schema: "gbizinfo_staging",
  tags: ["daily"]
}

SELECT
  CURRENT_DATE("Asia/Tokyo") - MAX(COALESCE(
    gbizinfo_staging.to_date(REGEXP_EXTRACT(fiscal_year_cover_page, r"^自.+至(.+)$")),
    gbizinfo_staging.to_date(REGEXP_EXTRACT(fiscal_year_cover_page, r"^.+から(.+)まで$")),
    ERROR("Unsupported fiscal_year_cover_page: " || IFNULL(fiscal_year_cover_page, "null"))
  )) AS delay,
FROM
  ${ref("gbizinfo_staging", "finance")}
HAVING
  INTERVAL 102 DAY < delay
