config {
  type: "operations",
  schema: "gbizinfo_staging",
  tags: ["gbizinfo/finance.csv"],
  hasOutput: true,
}

LOAD DATA OVERWRITE ${self()}
  (
    corporate_number STRING,
    name__corporate_number STRING,
    location__corporate_number STRING,
    name STRING,
    location STRING,
    accounting_standards STRING,
    fiscal_year_cover_page STRING,
    period STRING,
    net_sales_summary_of_business_results STRING,
    net_sales_summary_of_business_results_unit_ref STRING,
    operating_revenue1_summary_of_business_results STRING,
    operating_revenue1_summary_of_business_results_unit_ref STRING,
    operating_revenue2_summary_of_business_results STRING,
    operating_revenue2_summary_of_business_results_unit_ref STRING,
    gross_operating_revenue_summary_of_business_results STRING,
    gross_operating_revenue_summary_of_business_results_unit_ref STRING,
    ordinary_income_summary_of_business_results STRING,
    ordinary_income_summary_of_business_results_unit_ref STRING,
    net_premiums_written_summary_of_business_results_ins STRING,
    net_premiums_written_summary_of_business_results_ins_unit_ref STRING,
    ordinary_income_loss_summary_of_business_results STRING,
    ordinary_income_loss_summary_of_business_results_unit_ref STRING,
    net_income_loss_summary_of_business_results STRING,
    net_income_loss_summary_of_business_results_unit_ref STRING,
    capital_stock_summary_of_business_results STRING,
    capital_stock_summary_of_business_results_unit_ref STRING,
    net_assets_summary_of_business_results STRING,
    net_assets_summary_of_business_results_unit_ref STRING,
    total_assets_summary_of_business_results STRING,
    total_assets_summary_of_business_results_unit_ref STRING,
    number_of_employees STRING,
    number_of_employees_unit_ref STRING,
    name_major_shareholders1 STRING,
    shareholding_ratio1 STRING,
    name_major_shareholders2 STRING,
    shareholding_ratio2 STRING,
    name_major_shareholders3 STRING,
    shareholding_ratio3 STRING,
    name_major_shareholders4 STRING,
    shareholding_ratio4 STRING,
    name_major_shareholders5 STRING,
    shareholding_ratio5 STRING,
  )
  OPTIONS (
    description = "gs://${dataform.projectConfig.vars.bucketEventarc}/gbizinfo/finance.csv"
  )
  FROM FILES(
    allow_quoted_newlines=TRUE,
    format = 'CSV',
    uris = ['gs://${dataform.projectConfig.vars.bucketEventarc}/gbizinfo/finance.csv'],
    skip_leading_rows = 1
  )
  WITH CONNECTION `${dataform.projectConfig.vars.connectionID}`
