config {
  type: "operations",
  schema: "shukujitsu_staging",
  tags: ["syukujitsu.csv"],
  hasOutput: true,
}

LOAD DATA OVERWRITE ${self()}
  (
    date STRING,
    name STRING,
  )
  OPTIONS (
    description = "gs://${dataform.projectConfig.vars.bucketEventarc}/syukujitsu.csv"
  )
  FROM FILES(
    format = 'CSV',
    uris = ['gs://${dataform.projectConfig.vars.bucketEventarc}/syukujitsu.csv'],
    skip_leading_rows = 1
  )
  WITH CONNECTION `${dataform.projectConfig.vars.connectionID}`
