config {
  type: "operations",
  schema: "shukujitsu_staging",
  tags: ["syukujitsu.csv"],
  hasOutput: true,
}

CREATE OR REPLACE EXTERNAL TABLE ${self()} (
  date STRING,
  name STRING,
)
  WITH CONNECTION `${dataform.projectConfig.vars.connectionID}`
  OPTIONS (
    allow_quoted_newlines=TRUE,
    format = 'CSV',
    uris = ['gs://${dataform.projectConfig.vars.bucketSource}/syukujitsu.csv'],
    skip_leading_rows = 1)
